services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000

  dashboard:
    build:
      context: ./dashbaord
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
