import type { Locale, LoginContent } from "@/types/login";

export const translations: Record<Locale, LoginContent> = {
  en: {
    restaurant: "Restaurant",
    welcome: "Welcome",
    heroTitle: "Welcome back, chef.",
    heroText: "Run the floor, manage reservations, and keep your service moving smoothly.",
    dashboard: "Dashboard",
    admin: "Admin access",
    signIn: "Sign in",
    manage: "Manage your restaurant",
    email: "Email address",
    password: "Password",
    remember: "Remember me",
    forgot: "Forgot password?",
    submit: "Sign in to dashboard",
    invite: "Need access?",
    inviteAction: "Request admin invite",
    requestAccessTitle: "Request admin access",
    requestAccessText: "Tell us a little about yourself and we will review your request.",
    fullName: "Full name",
    requestReason: "Why do you need access?",
    placeholderName: "Your name",
    placeholderReason: "Tell us about your role",
    sendRequest: "Send request",
    requestSent: "Request sent",
    requestSentText: "We will be in touch after reviewing your request.",
    close: "Close",
    placeholderEmail: "name@restaurant.com",
    placeholderPassword: "Enter your password",
  },
  hi: {
    restaurant: "रेस्टोरेंट",
    welcome: "स्वागत",
    heroTitle: "फिर से स्वागत है, शेफ।",
    heroText: "फ्लोर संभालें, रिज़र्वेशन प्रबंधित करें और अपनी सेवा को सुचारू रखें।",
    dashboard: "डैशबोर्ड",
    admin: "एडमिन एक्सेस",
    signIn: "साइन इन",
    manage: "अपने रेस्टोरेंट का प्रबंधन करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    remember: "मुझे याद रखें",
    forgot: "पासवर्ड भूल गए?",
    submit: "डैशबोर्ड में साइन इन करें",
    invite: "एक्सेस की जरूरत है?",
    inviteAction: "एडमिन इनवाइट का अनुरोध करें",
    requestAccessTitle: "एडमिन एक्सेस का अनुरोध करें",
    requestAccessText: "अपने बारे में थोड़ा बताएं और हम आपके अनुरोध की समीक्षा करेंगे।",
    fullName: "पूरा नाम",
    requestReason: "आपको एक्सेस क्यों चाहिए?",
    placeholderName: "अपना नाम लिखें",
    placeholderReason: "अपनी भूमिका के बारे में बताएं",
    sendRequest: "अनुरोध भेजें",
    requestSent: "अनुरोध भेज दिया गया",
    requestSentText: "आपके अनुरोध की समीक्षा के बाद हम आपसे संपर्क करेंगे।",
    close: "बंद करें",
    placeholderEmail: "name@restaurant.com",
    placeholderPassword: "अपना पासवर्ड लिखें",
  },
};

export type { Locale, LoginContent } from "@/types/login";
