export const translations = {
  en: {
    restaurant: "Restaurant",
    welcome: "Welcome",
    heroTitle: "Welcome back, chef.",
    heroText: "Run the floor, manage reservations, and keep your service moving smoothly.",
    dashboard: "Dashboard",
    admin: "Admin access",
    signIn: "Sign in",
    manage: "Manage your restaurant",
    email: "Email address",
    password: "Password",
    remember: "Remember me",
    forgot: "Forgot password?",
    submit: "Sign in to dashboard",
    divider: "or continue with",
    invite: "Need access?",
    inviteAction: "Request admin invite",
    placeholderEmail: "name@restaurant.com",
    placeholderPassword: "Enter your password",
  },
  hi: {
    restaurant: "रेस्टोरेंट",
    welcome: "स्वागत",
    heroTitle: "फिर से स्वागत है, शेफ।",
    heroText: "फ्लोर संभालें, रिज़र्वेशन प्रबंधित करें और अपनी सेवा को सुचारू रखें।",
    dashboard: "डैशबोर्ड",
    admin: "एडमिन एक्सेस",
    signIn: "साइन इन",
    manage: "अपने रेस्टोरेंट का प्रबंधन करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    remember: "मुझे याद रखें",
    forgot: "पासवर्ड भूल गए?",
    submit: "डैशबोर्ड में साइन इन करें",
    divider: "या इसके साथ जारी रखें",
    invite: "एक्सेस की जरूरत है?",
    inviteAction: "एडमिन इनवाइट का अनुरोध करें",
    placeholderEmail: "name@restaurant.com",
    placeholderPassword: "अपना पासवर्ड लिखें",
  },
} as const;

export type Locale = keyof typeof translations;
